FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/Arsalan010officiall/A-R-S-L-A-N-MD-BOT /root/SamPandey001
WORKDIR /root/Arsalan010officiall/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
